version: '3.9'

services:

  postgres:
    container_name: devops_demo_postgres_db
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
        #command: sh -c "poetry run python manage.py makemigrations &&
        #           poetry run python manage.py migrate"
    ports:  
      - "5432:5432"

  web_app:
    container_name: devops_demo_app
    build:
      context: .
      dockerfile: Dockerfile
        #command: sh -c "poetry run python manage.py runsesrver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - .:/devops_demo
    env_file:
      - ./.env.dev
    depends_on:
      - postgres 

volumes:
  postgres_data:
