version: '3'

services:


  postgres:
    container_name: devops_demo_postgres_db
    image: postgres:13.0-alpine
    env_file:
      - .env.postgres
    networks:
      - devops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:  
      - "5432:5432"


  web_app:
    container_name: devops_demo_app
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py createsuperuser --no-input
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - postgres
    networks:
      - devops 


  nginx:
    container_name: devops_demo_nginx
    build:
      context: ./nginx
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web_app
    networks:
      - devops


volumes:
  postgres_data:

networks:
  devops:
